### ISSUE TITLE
Restart Workers

### ISSUE THREAD

**Issue by kelunik** [amphp/cluster#3]
We have to implement worker restarts and graceful reloading, preferably with zero downtime.

**Comment by brstgt** [comment]
Proposal for graceful restart:
- Watcher spawns new workers, old workers are tagged as "shutting down" by moving to a new collection like "shuttingDownWorkers"
- Watcher sends "shut down" message to old workers
- Worker reacts to "shut down" message, initiates graceful shutdown and simply stops when they are done
- Watcher kills a worker after $gracefulShutdownTimeout

Graceful shutdown:
Same as graceful restart except that watcher does not spawn new workers

**Comment by brstgt** [comment]
I would not do this. What if shutting down a worker takes 10s (ending longer running requests gracefully). If you have 30 workers that could take 300s. Doing that in parallel would take 10s.
My proposal also has no downtime.

**Comment by kelunik** [comment]
@joelwurtz Sure. ;-)

**Comment by trowski** [comment]
This has been implemented - both automatic restarts of workers and explicit restarting of the cluster.

If a worker dies unexpectedly, the `Watcher` instance automatically starts a new process to replace it. There are two examples demonstrating this: [`failing-process.php`](https://github.com/amphp/cluster/blob/45387573b0e5abf650a0d81483ebab61f42633a9/examples/failing-process.php) calls `exit` in the worker and [`out-of-memory.php`](https://github.com/amphp/cluster/blob/45387573b0e5abf650a0d81483ebab61f42633a9/examples/out-of-memory.php) concatenates huge strings until running out of memory.

The entire cluster can be restarted using [`Watcher::restart()`](https://github.com/amphp/cluster/blob/45387573b0e5abf650a0d81483ebab61f42633a9/src/Watcher.php#L251-L282) or sending [`SIGUSR1` to `bin/cluster`](https://github.com/amphp/cluster/blob/master/bin/cluster#L189-L198).  The first use I can think of for this feature is reloading code changes without shutting down the main watcher process. As a thought, a filesystem monitor could be coupled with this to automatically restart a worker when files in a project change.

Please give this package a try. I'd appreciate feedback and bug reports.
