### ISSUE TITLE
How to bench this cluster?

### ISSUE THREAD

**Issue by andreybolonin** [amphp/cluster#6]
`wrk -t4 -c400 -d10s tcp://127.0.0.1:1337`

<img width="538" alt="screen shot 2018-06-29 at 11 33 46 am" src="https://user-images.githubusercontent.com/2576509/42082311-5554a95c-7b90-11e8-80e0-b1607e75f910.png">

But worker accept the requests
<img width="655" alt="screen shot 2018-06-29 at 11 34 51 am" src="https://user-images.githubusercontent.com/2576509/42082375-7bb8a292-7b90-11e8-89d6-3db4366218c6.png">

**Comment by kelunik** [comment]
What's the code you're running?

**Comment by andreybolonin** [comment]
`bin/cluster -s examples/hello-world.php`

**Comment by bwoebi** [comment]
This is not a http server, but a simple socket.
To bench with wrk, you actually need to integrate amphp/http-server with cluster.
